#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Deployment"})
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      tolerations:
      #@overlay/match by="key", missing_ok=True
      - 
        effect: NoSchedule
        key: node-role.kubernetes.io/master
